GET http://localhost:4004/catalog/
###
GET http://localhost:4004/catalog/$metadata
###
GET http://localhost:4004/catalog/Sales
###
DELETE http://localhost:4004/catalog/Sales(5)
Authorization: Basic joe:
###
POST http://localhost:4004/catalog/Sales(1)/CatalogService.boost
Content-Type: application/json

{}
###
GET http://localhost:4004/catalog/Sales?$apply=filter(amount%20gt%20500)/groupby((region),aggregate($count%20as%20nrCountries))
###
GET http://localhost:4004/catalog/topSales(amount=700)
###
GET http://localhost:4004/catalog/VSales
###
GET http://localhost:4004/catalog/SessionInfo
###
GET http://localhost:4004/catalog2/Students?$top=10
###
